-- Group each Spanish club's layouts under one club.
--
-- Generated by scripts/buildSpainClubsMigration.js from
-- scripts/data/spain-courses.json and the library. Do not edit by hand.
--
-- The course picker shows a club with two or more layouts as one row and
-- lets the round pick the layout (layout_name). Courses seeded before the
-- federation import carried no club, so a club's layouts sat side by side.
-- Each federation club's courses now share a club; a course keeps any
-- layout_name it already had. Course names and ids do not change.


UPDATE public.courses c
   SET club_id = v.club_id::uuid,
       layout_name = COALESCE(c.layout_name, v.layout_name)
  FROM (VALUES
  ('538ec7ed-2659-4964-b59f-974fa0b381c6', '180349fb-5f7d-5f01-ae2f-82c4e6c7ecd5', 'Alborán'),
  ('56f150fc-8cd3-4a91-b4ec-2f0c6a60e621', 'a2c8e1e2-0100-5f18-9e3d-7ef1efa8817c', 'Aldeamayor'),
  ('f408cb94-8b48-48d2-8f6e-3543014ab023', 'ad35bfd3-d358-5af4-a25b-b3c19eb0773f', 'Aloha'),
  ('b87a87f8-52a1-4976-9279-0a153b718783', 'd335593f-04a5-5eca-a88c-1a235f0b0f86', 'Anfi Tauro'),
  ('df9b8529-0918-4da3-adf1-b54690c9eb85', '61420841-5e85-5b88-9f33-b00b4ee52c8c', 'Old Course'),
  ('b294406d-f275-46de-ad15-1d8e404ad43d', '91851659-323c-5c5e-9939-6b9ef5352941', 'Cabanillas Casa De Campo Golf'),
  ('25c10dc7-9566-48e7-a488-18d851efec56', 'e3f29fca-08e8-5502-b7d2-00a82bd3895c', 'Cabopino'),
  ('e8e0a264-d6fb-4045-a3ba-91f559c0ea85', '3eaa9554-2deb-597a-9e46-12f71d2b9e28', 'Abra del Pas'),
  ('012b8076-6eea-4fdb-8339-50e0c1bf5012', '9de161b8-8d02-53fa-a6ca-70a9f7fbb6ce', 'Oyambre'),
  ('6ac6ae93-cd28-4de1-a22d-d7c115080d1a', '2ff6ab69-0380-5602-8272-3c891c7b374e', 'Talayuela'),
  ('5e657d4b-6f69-4bef-96ea-2ef6af3fe367', '137dce10-efb4-585d-8398-92bc3c7e7d3e', 'Meaztegi'),
  ('716e70dd-54ce-424f-b7c9-af3673a9ba50', '980f9172-90b8-59c2-b0d9-aa1512c2af1b', 'Oliva Nova'),
  ('b786a3e1-2bb5-46e9-8158-c39272cbf7cc', '5d03f8fc-3c9b-5649-bc0d-495aa5e66103', 'Galisteo'),
  ('0772e355-8dd2-415e-9e26-2879986dbbc5', 'f55b5ae2-4d29-5582-b2b7-6a44a764fa0c', 'La Galera'),
  ('d98b82ed-8354-42be-8e8c-eb43139d1051', '82fd588f-4ab1-53da-85d7-8f7c74ac0a04', 'A+B'),
  ('79900ce6-baa8-4cfe-b84a-82c0dd99e085', 'c9d1de64-0496-537d-87a5-643906aec68c', 'Alcanada'),
  ('8005d5b0-ed61-445b-958f-c19fc7b5f482', 'ab8c1452-72ee-5d19-bc24-a1edf20f80db', 'Bellavista'),
  ('69bf6b1e-1c94-440d-b1d6-64668cd63e13', '9b4d5254-98bd-5363-81b6-97921dfaa5da', 'A Verde'),
  ('a857cba8-9ab5-40db-90b9-c8b85d285ba5', '0fd8339c-e737-5b55-a8bf-2ddb306decb1', 'Old Course'),
  ('4dd62bdb-108e-49fc-a503-396154d42572', 'b37be34b-bd2c-56fd-9c39-39e1bd56a765', 'Logroño'),
  ('02c82369-1312-465d-b6e7-fe9a19dc9764', '26541493-fcd3-5fcb-8b79-6a04c7f9d7bc', 'Old Course'),
  ('5b8abcf1-e8f0-4f99-b808-94766d6f4865', '14085267-606d-5107-ac48-f3fe38044df2', 'Masia+Lagos'),
  ('fffe2aa3-6832-441d-bccc-adb8604f2d4d', '766581aa-8e30-595b-8934-46f70d364e8b', 'Font Del Llop'),
  ('ab85c8ce-528f-4c99-9251-9d7c21dc4d33', '9e87bdd1-f724-56aa-ba9a-f7bed2b6630d', 'La Cañada'),
  ('b1f8c2ae-b9f2-4eeb-955f-45e9d1ab8a16', '96fb593d-47da-54c6-b475-c7691308eab6', 'Playa Serena'),
  ('8b82bd7f-1729-4f3a-a672-ae8ff886e295', 'b3d5837d-c809-523e-87a3-7893a00d7597', 'Ria De Vigo Golf'),
  ('a1f750d4-aabd-435f-bb3f-3475adab1efb', 'a4b03233-6810-5097-8696-a7b7cb2ece20', 'Terramar'),
  ('94c642e7-523c-474e-9ee9-43f7608f8fa4', '4b90b9ad-5930-50c0-84a3-b74fa909016b', 'Vallromanes'),
  ('d695ffd5-2912-418f-abe7-812aad3685eb', 'de067437-8427-5148-8c86-a1ba61089c66', 'Añoreta Golf'),
  ('a8a02789-53c9-486c-84af-74a81f8c729b', 'a7d3a2b8-1fda-53c3-a6a6-0246961a4d5c', 'Hato Verde'),
  ('1dafa5f6-c9b4-472d-a8e9-b2081d54c72f', 'f4036d8c-853e-56ef-bd50-800c3fe3821b', 'La Valmuza'),
  ('5a1d93dd-aefb-499c-a226-830af2574803', '24414a60-20b4-57cb-b58f-df1e946ec4d7', 'Marina Golf'),
  ('578afa02-f5bb-495e-9904-4cd814599249', 'e8e86cf6-30a6-5397-a396-8fcbd4bdd6d5', 'Palmeras + Ficus'),
  ('1e432d8c-a13f-4ad1-8af3-579403d1d862', '0adc8af7-c11f-54e8-92dc-e4df4f4a4fb8', 'Don Tello'),
  ('dfeaa675-d821-4be4-9d0e-c20a0fa6e18b', '55978b31-fec8-5a68-bf5d-231c1f17e1d5', 'El Chaparral'),
  ('bdb04ba8-797b-4d9c-891a-2ef4ca6e7883', '98a31c45-5f82-50f5-afae-72b7209023e8', 'Dunes'),
  ('bec9c855-fb49-4919-8475-df152d549311', '59736d42-746c-5528-be7e-bef01d5a74b3', 'Calatayud'),
  ('2baa7286-6c36-4e2a-ad99-0102a27c7485', 'c6bdeed8-f899-5a8b-b796-38a9d240ea7d', 'Azul+Blanco'),
  ('ea279bf2-52ee-4bce-b0bd-ba319b7257f1', '09b10642-4a66-52a3-99c2-c6cb14aa8541', 'Golf Ciudad Real'),
  ('202dae6b-802a-4d77-adba-e3dd1cd2f6d7', 'cf181ad6-b9bf-526d-9349-0a1178cbcb16', 'Championship Course'),
  ('61523283-885d-4e31-a5b2-a98d49637d85', 'bcad98ab-2f19-57f0-a756-94040ffe539f', 'Golf Guadiana'),
  ('74e0cb12-f5c4-466f-95ac-5a27721558f3', 'dc0fed87-f52c-5366-ad21-ba14c37a2758', 'Norte + Links'),
  ('1a3dab40-c551-4451-ad4f-c364548561ac', 'c7580756-26f5-5720-804e-9b4cf9295019', 'Playa de Pals'),
  ('64876d6b-8e27-4979-aac4-e34e4e935c9e', '458f8740-08bd-570f-a35e-9e995d3d7431', 'Río Real'),
  ('ddeaef1f-74c8-4320-a865-1f824d20a0e5', 'c12012ae-fa0c-50cf-990c-baa892149084', 'Santa Ponsa I'),
  ('f0694178-e942-45ed-bed1-1558c4c1ca35', '4749854a-31df-5147-a418-d5cb2fd4f267', 'Granada'),
  ('bad8d8aa-cab7-48e9-8eca-9130cffe2799', '77d919e7-f120-58f6-9457-70fb4e83303c', 'Grijota Golf'),
  ('80f85247-17db-4060-a479-ced28fd66168', 'ffb552da-f50c-51b3-94f4-856817fe39e4', 'Isla Canela'),
  ('7aaedf85-5ee8-4695-b404-b5d917b1e124', 'b24fd2d6-9c59-5fb6-afb2-d30f986f3651', 'Amarillo+Verde'),
  ('d1bb1025-4a2a-4b51-a336-91c79b663b87', '1ef3c9af-5654-58e1-a540-100f38672fdd', 'Campo Asia'),
  ('879f118e-39bb-45df-badb-7f05ded2330f', '1ef3c9af-5654-58e1-a540-100f38672fdd', 'Campo America'),
  ('a5dfdb1a-8223-4fa5-8d92-4cb12ec1903a', '1ef3c9af-5654-58e1-a540-100f38672fdd', 'Campo Europa'),
  ('a3541101-3085-4eea-a37c-0cf9be94aa42', 'e2016ec2-bd47-5ef0-ae62-8e4e6d225565', 'La Envía'),
  ('6a77b4ac-51a4-4f1c-847d-61723e50033f', '45ae7fc2-d044-56ea-82e9-14671e5b42b2', 'Links'),
  ('4e4830f1-0e59-4b68-a91c-530fbfe4fae3', '53373550-37b7-5506-9259-1bb0d6023457', 'San Pedro+Ronda'),
  ('1fd3b287-0741-4c5c-b771-f31efc9b243b', '2e10d419-8093-5738-a87d-a3c11a7b5323', 'Gregal+Mestral'),
  ('d0bcf03b-267d-4cb7-8937-91577251891f', '7e899242-bbc1-511a-8902-18b6ab3403d7', 'Leon Golf-Prosacyr'),
  ('40d642f4-43d8-42c3-88ec-822ecafe4cf5', '44022481-0dda-5b4c-8df1-d1aec0424152', 'Los Moriscos Golf'),
  ('0f93cab5-8e3d-47b7-acd5-8a5f3b9ebc6c', '7faa35a9-f6cf-5ca1-aa42-35e30289bcd1', 'Los Naranjos'),
  ('106f4366-f6ab-4d79-9c5c-37b70e5738f8', '7c761e34-4d27-5964-ab9d-fe2def3a52c7', 'Las Margas'),
  ('b9a62618-385f-43a4-adc2-3913da04a5bd', 'f90d1d82-ad1f-548c-ba5b-d9e165c33987', 'Mediterraneo'),
  ('0b86b00d-ff04-46a5-ad44-bf35f455683e', 'd308e74d-df35-5b50-8c1e-fed0fd1ebee1', 'Miño Artabro'),
  ('c1b76b16-7d9e-4b6e-b655-f7d14c0bcaea', 'e0bf564d-4755-5c69-b7b8-ee3377991bd0', 'Norba Golf'),
  ('e389d916-ffeb-4c5a-adcd-7734b1e405b7', '5c4ac260-b1a3-5761-ac58-82f6ce2c5fa8', 'Parraluz'),
  ('2a0f4c6f-9a34-48a0-801a-26c0475f04a1', 'a83730b8-c523-5b2a-8a74-1cc5c7dded18', 'Rac Vigo Par 70'),
  ('edce2788-883e-4261-811a-148a6d83cf61', '5ba5b6cc-2bfb-5527-a8ed-59929f1502ae', 'A+A'),
  ('07403f05-9f27-4b87-b82d-8e16cdd035b6', '33957f2c-e90d-5c35-abd8-ddba1b85ef58', 'Rosa'),
  ('1dbe2a7b-ce3f-407e-b9e4-b17a474abc9e', '893c1115-0e72-5163-a782-c3993e0f423b', 'Sur'),
  ('fd2b84f1-6996-401a-a449-271aee56bb23', '3a0e8131-5a48-53a9-a1be-7c166e9f692a', 'Rc Pineda'),
  ('15d3d0fd-c4ff-496e-a3f4-ebf7d8e9fe5a', '12ae6d7c-717e-54a9-b4c4-47b490aeca3d', 'Recorrido 1'),
  ('cadb60ad-c58c-400b-94c3-0b6a288b96ba', '75455935-c5c3-53aa-baa3-d2ad7e09f71c', 'Rgc San Sebastian'),
  ('e8685fa9-f9bd-4378-aee9-15617dfd218b', 'da0dc8d1-3ffc-5bee-b968-4b4153a12910', 'Montealegre'),
  ('20c4e1f2-5402-47bd-85d2-9c65bf6432ee', 'f1483b2c-45e7-5643-8535-b8027ceeb1e8', 'Rioja Alta'),
  ('598ad5b4-be14-4648-97f2-7a8fe535ca76', 'c87206b6-f1c8-5050-b3c3-2452fe23d18a', 'Villamayor'),
  ('d1de4df2-9747-42b5-9cfe-8139a56048ff', '53083dde-43de-52c9-82af-8a56a7c772e5', 'Santa Clara Granada'),
  ('97c3c94b-1e4a-4e58-a520-968f9e735dc2', '645cb5f9-47d2-50e5-9c03-a672f6ecfe0f', 'Seve Ballesteros Lavin La Junquera'),
  ('887beda1-dbe8-408b-b61d-0578de58ae8c', 'a24f1dc6-810f-5418-90e8-ac0d18b56054', 'Sherry Golf'),
  ('d0739398-7b9b-4f3a-96bb-a5a545dfb746', 'e4fe9653-95c2-5214-9123-f56a6e6c23ef', 'Valle Del Este Golf')
) AS v(id, club_id, layout_name)
 WHERE c.id = v.id::uuid
   AND EXISTS (SELECT 1 FROM public.clubs k WHERE k.id = v.club_id::uuid);
