-- Spanish courses from the Real Federación Española de Golf (second pass).
--
-- Five layouts the first import (20261006000001) wrongly took for an existing
-- course: generic words such as "Escuela" or "Centro" matched them to the Madrid
-- federation school. Those words no longer count as a name match.
--
-- Generated by scripts/buildSpainCoursesMigration.js from
-- scripts/data/spain-courses.json (fetched with scripts/fetchSpainCourses.js
-- from rfegolf.es/club/<club>). Do not edit by hand — regenerate.
--
-- Adds every federation recorrido the library did not already have: holes
-- with the men's stroke index, and one tee per colour carrying the official
-- WHS rating/slope for men and women, longest tee first, metres per hole in
-- yardages. A layout already in the library (same par on every hole, and the
-- same stroke index or a shared name word) is left untouched.
--
-- Ids are stable, and every insert is guarded, so applying twice is a no-op.

INSERT INTO public.clubs (id, name, city, province) VALUES
  ('6ab164de-94e3-5129-9ea5-b1ab86dd5abf', 'Escuela de Golf Elche', 'Elche', 'Valencian Community'),
  ('cd184dd5-08b2-584e-a601-1ed0bf019de5', 'Escuela Pública la Cartuja', NULL, 'Andalusia')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.courses (id, name, city, province, club_id, layout_name)
SELECT v.id::uuid, v.name, v.city, v.province, v.club_id::uuid, v.layout_name FROM (VALUES
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 'Escuela de Golf Elche — El Palmeral', 'Elche', 'Valencian Community', '6ab164de-94e3-5129-9ea5-b1ab86dd5abf', 'El Palmeral'),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 'Escuela de Golf Elche — El Misteri', 'Elche', 'Valencian Community', '6ab164de-94e3-5129-9ea5-b1ab86dd5abf', 'El Misteri'),
  ('9fe70b37-7959-5140-9547-0681215786b4', 'Escuela de Golf Miguel Ángel Jiménez', 'Torremolinos', 'Andalusia', NULL, NULL),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 'Escuela Pública la Cartuja — P&P', NULL, 'Andalusia', 'cd184dd5-08b2-584e-a601-1ed0bf019de5', 'P&P'),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 'Lizaso Centro de Golf', 'Lizaso', 'Navarre', NULL, NULL)
) AS v(id, name, city, province, club_id, layout_name)
WHERE NOT EXISTS (SELECT 1 FROM public.courses c WHERE c.id = v.id::uuid OR lower(c.name) = lower(v.name));

INSERT INTO public.course_holes (course_id, number, par, stroke_index)
SELECT v.course_id::uuid, v.number, v.par, v.si FROM (VALUES
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 1, 3, 10),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 2, 3, 14),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 3, 3, 8),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 4, 3, 18),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 5, 3, 12),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 6, 3, 16),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 7, 3, 2),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 8, 3, 6),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 9, 3, 4),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 10, 3, 11),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 11, 3, 9),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 12, 3, 13),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 13, 3, 15),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 14, 3, 17),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 15, 3, 5),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 16, 3, 3),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 17, 3, 1),
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 18, 3, 7),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 1, 3, 10),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 2, 3, 18),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 3, 3, 8),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 4, 3, 6),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 5, 3, 16),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 6, 3, 14),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 7, 3, 12),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 8, 3, 2),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 9, 3, 4),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 10, 3, 15),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 11, 3, 5),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 12, 3, 13),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 13, 3, 3),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 14, 3, 17),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 15, 3, 7),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 16, 3, 9),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 17, 3, 1),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 18, 3, 11),
  ('9fe70b37-7959-5140-9547-0681215786b4', 1, 3, 17),
  ('9fe70b37-7959-5140-9547-0681215786b4', 2, 3, 15),
  ('9fe70b37-7959-5140-9547-0681215786b4', 3, 3, 9),
  ('9fe70b37-7959-5140-9547-0681215786b4', 4, 3, 5),
  ('9fe70b37-7959-5140-9547-0681215786b4', 5, 3, 7),
  ('9fe70b37-7959-5140-9547-0681215786b4', 6, 3, 13),
  ('9fe70b37-7959-5140-9547-0681215786b4', 7, 3, 1),
  ('9fe70b37-7959-5140-9547-0681215786b4', 8, 3, 3),
  ('9fe70b37-7959-5140-9547-0681215786b4', 9, 3, 11),
  ('9fe70b37-7959-5140-9547-0681215786b4', 10, 3, 18),
  ('9fe70b37-7959-5140-9547-0681215786b4', 11, 3, 16),
  ('9fe70b37-7959-5140-9547-0681215786b4', 12, 3, 10),
  ('9fe70b37-7959-5140-9547-0681215786b4', 13, 3, 6),
  ('9fe70b37-7959-5140-9547-0681215786b4', 14, 3, 8),
  ('9fe70b37-7959-5140-9547-0681215786b4', 15, 3, 14),
  ('9fe70b37-7959-5140-9547-0681215786b4', 16, 3, 2),
  ('9fe70b37-7959-5140-9547-0681215786b4', 17, 3, 4),
  ('9fe70b37-7959-5140-9547-0681215786b4', 18, 3, 12),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 1, 3, 16),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 2, 3, 8),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 3, 3, 12),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 4, 3, 4),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 5, 3, 5),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 6, 3, 17),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 7, 3, 3),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 8, 3, 14),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 9, 3, 15),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 10, 3, 6),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 11, 3, 9),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 12, 3, 10),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 13, 3, 2),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 14, 3, 11),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 15, 3, 13),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 16, 3, 1),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 17, 3, 7),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 18, 3, 18),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 1, 3, 5),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 2, 3, 14),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 3, 3, 8),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 4, 3, 2),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 5, 3, 11),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 6, 3, 6),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 7, 3, 15),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 8, 3, 16),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 9, 3, 9),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 10, 3, 12),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 11, 3, 1),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 12, 3, 3),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 13, 3, 18),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 14, 3, 10),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 15, 3, 17),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 16, 3, 4),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 17, 3, 13),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 18, 3, 7)
) AS v(course_id, number, par, si)
WHERE EXISTS (SELECT 1 FROM public.courses c WHERE c.id = v.course_id::uuid)
  AND NOT EXISTS (SELECT 1 FROM public.course_holes h WHERE h.course_id = v.course_id::uuid AND h.number = v.number);

INSERT INTO public.course_tees (course_id, label, rating, slope, rating_women, slope_women, sort_order, yardages)
SELECT v.course_id::uuid, v.label, v.rating, v.slope, v.rating_women, v.slope_women, v.sort_order, v.yardages::jsonb FROM (VALUES
  ('b67814a2-6c9d-5fd3-bc45-e9bb588e8694', 'Verdes', 49.2, 55, 50.3, 56, 0, '{"1":67,"2":50,"3":69,"4":40,"5":62,"6":52,"7":81,"8":72,"9":74,"10":51,"11":60,"12":51,"13":46,"14":45,"15":65,"16":66,"17":94,"18":62}'),
  ('1b1cf725-ed26-57ca-a9cf-b9d668d495f3', 'Verdes', 50, 55, 51.2, 60, 0, '{"1":67,"2":60,"3":84,"4":46,"5":62,"6":52,"7":81,"8":94,"9":95,"10":51,"11":65,"12":69,"13":92,"14":45,"15":65,"16":66,"17":120,"18":74}'),
  ('9fe70b37-7959-5140-9547-0681215786b4', 'Verdes', 50.8, 66, 52.6, 75, 0, '{"1":73,"2":73,"3":114,"4":83,"5":104,"6":54,"7":119,"8":111,"9":85,"10":73,"11":73,"12":114,"13":83,"14":104,"15":54,"16":119,"17":111,"18":85}'),
  ('60f5514a-73d6-54cd-b4d9-5a970c176bf5', 'Verdes', 51.2, 55, 52.6, 64, 0, '{"1":67,"2":114,"3":107,"4":102,"5":70,"6":73,"7":103,"8":50,"9":76,"10":86,"11":95,"12":120,"13":103,"14":111,"15":91,"16":118,"17":77,"18":89}'),
  ('3a868816-dc06-540f-a1fb-5554db0f820e', 'Verdes', 50.1, 57, 51.6, 63, 0, '{"1":64,"2":86,"3":78,"4":102,"5":70,"6":101,"7":79,"8":58,"9":71,"10":44,"11":110,"12":103,"13":71,"14":97,"15":66,"16":111,"17":78,"18":72}')
) AS v(course_id, label, rating, slope, rating_women, slope_women, sort_order, yardages)
WHERE EXISTS (SELECT 1 FROM public.courses c WHERE c.id = v.course_id::uuid)
  AND NOT EXISTS (SELECT 1 FROM public.course_tees t WHERE t.course_id = v.course_id::uuid AND t.label = v.label);
